### ISSUE TITLE
Firefox 

### ISSUE THREAD

**Issue by skerbis** [YanshuoH/jQuery-simple-parallax#1]
On Firefox i get the Error TypeError: $this.css(...) is undefined, all other Browsers work nice. 

The Error seems to be here
 if ($this.css(name).search('%') > -1) {
            originalValue = parseInt(originalCssValue.replace('%', ''));
        } else if ($this.css(name).search('px') > -1) {
            originalValue = parseInt(originalCssValue.replace('px', ''));
        }

**Comment by YanshuoH** [comment]
@skerbis  Thanks for report, this is a known problem [background-position](http://stackoverflow.com/questions/14844407/background-position-y-doesnt-work-in-firefox-via-css) with Firefox. (And I've kind of ignored it when developing this script)

Since Firefox does not understand **background-position-y** and **background-position-x**, I'll work out a generic solution to deal with it.

**Comment by skerbis** [comment]
that would be nice, because i can't find realy an alternative for my website. Do you know a good and "easy" :-) alternative? I need it only for Backgrounds inside a div.

**Comment by YanshuoH** [comment]
@skerbis As far as I know...not really...you may want to create your own option for this script, using a dispatcher event of bg-position-x and bg-position-y. Or you may want to wait for a day till I have time to correct this bug.

**Comment by skerbis** [comment]
Thank you. I will wait.

**Comment by YanshuoH** [comment]
@skerbis fixed

**Comment by skerbis** [comment]
THX :+1:
